import type { Task, Label, Comment } from '@doist/todoist-api-typescript'
import type { Project, Section } from '../../lib/api/core.js'

const taskDefaults = {
  isUncompletable: false,
  userId: 'user-1',
  addedByUid: null,
  assignedByUid: null,
  responsibleUid: null,
  order: 0,
  createdAt: '2026-01-01T00:00:00Z',
  duration: null,
  isCollapsed: false,
  completedAt: null,
  addedAt: '2026-01-01T00:00:00Z',
  isDeleted: false,
  syncId: null,
  deadline: null,
  updatedAt: '2026-01-01T00:00:00Z',
  childOrder: 0,
  noteCount: 0,
  dayOrder: 0,
}

const commentDefaults = {
  fileAttachment: null,
  postedUid: 'user-1',
  uidsToNotify: [] as string[],
  reactions: {},
  isDeleted: false,
}

export const fixtures = {
  tasks: {
    basic: {
      ...taskDefaults,
      id: 'task-1',
      content: 'Buy milk',
      description: '',
      priority: 1,
      projectId: 'proj-1',
      sectionId: null,
      parentId: null,
      labels: [],
      due: null,
      checked: false,
      url: 'https://todoist.com/showTask?id=task-1',
    } as Task,
    withDue: {
      ...taskDefaults,
      id: 'task-2',
      content: 'Meeting',
      description: '',
      priority: 4,
      projectId: 'proj-1',
      sectionId: null,
      parentId: null,
      labels: ['work'],
      due: { date: '2026-01-09', string: 'today', isRecurring: false },
      checked: false,
      url: 'https://todoist.com/showTask?id=task-2',
    } as Task,
    overdue: {
      ...taskDefaults,
      id: 'task-3',
      content: 'Overdue task',
      description: '',
      priority: 2,
      projectId: 'proj-1',
      sectionId: null,
      parentId: null,
      labels: [],
      due: { date: '2026-01-01', string: 'Jan 1', isRecurring: false },
      checked: false,
      url: 'https://todoist.com/showTask?id=task-3',
    } as Task,
    completed: {
      ...taskDefaults,
      id: 'task-4',
      content: 'Done task',
      description: '',
      priority: 1,
      projectId: 'proj-1',
      sectionId: null,
      parentId: null,
      labels: [],
      due: null,
      checked: true,
      url: 'https://todoist.com/showTask?id=task-4',
    } as Task,
    withDescription: {
      ...taskDefaults,
      id: 'task-5',
      content: 'Task with notes',
      description: 'Some detailed description here',
      priority: 3,
      projectId: 'proj-1',
      sectionId: 'sec-1',
      parentId: null,
      labels: ['urgent', 'home'],
      due: { date: '2026-01-10', string: 'tomorrow', isRecurring: false },
      checked: false,
      url: 'https://todoist.com/showTask?id=task-5',
    } as Task,
  },
  projects: {
    inbox: {
      id: 'proj-inbox',
      name: 'Inbox',
      color: 'grey',
      isFavorite: false,
      parentId: null,
      viewStyle: 'list',
      url: 'https://todoist.com/app/project/proj-inbox',
    } as Project,
    work: {
      id: 'proj-work',
      name: 'Work',
      color: 'blue',
      isFavorite: true,
      parentId: null,
      viewStyle: 'board',
      url: 'https://todoist.com/app/project/proj-work',
    } as Project,
    personal: {
      id: 'proj-personal',
      name: 'Personal',
      color: 'green',
      isFavorite: false,
      parentId: null,
      viewStyle: 'list',
      url: 'https://todoist.com/app/project/proj-personal',
    } as Project,
  },
  sections: {
    planning: {
      id: 'sec-1',
      name: 'Planning',
      projectId: 'proj-work',
      sectionOrder: 1,
      url: 'https://todoist.com/app/section/sec-1',
    } as Section,
    inProgress: {
      id: 'sec-2',
      name: 'In Progress',
      projectId: 'proj-work',
      sectionOrder: 2,
      url: 'https://todoist.com/app/section/sec-2',
    } as Section,
    review: {
      id: 'sec-3',
      name: 'Review',
      projectId: 'proj-work',
      sectionOrder: 3,
      url: 'https://todoist.com/app/section/sec-3',
    } as Section,
  },
  labels: {
    urgent: {
      id: 'label-1',
      name: 'urgent',
      color: 'red',
      isFavorite: true,
    } as Label,
    home: {
      id: 'label-2',
      name: 'home',
      color: 'green',
      isFavorite: false,
    } as Label,
    work: {
      id: 'label-3',
      name: 'work',
      color: 'blue',
      isFavorite: false,
    } as Label,
  },
  comments: {
    basic: {
      ...commentDefaults,
      id: 'comment-1',
      content: 'First comment',
      taskId: 'task-1',
      projectId: undefined,
      postedAt: '2026-01-08T10:00:00Z',
    } as Comment,
    second: {
      ...commentDefaults,
      id: 'comment-2',
      content: 'Follow up note',
      taskId: 'task-1',
      projectId: undefined,
      postedAt: '2026-01-09T14:30:00Z',
    } as Comment,
    withAttachment: {
      ...commentDefaults,
      id: 'comment-3',
      content: 'See attached file',
      taskId: 'task-1',
      projectId: undefined,
      postedAt: '2026-01-09T16:00:00Z',
      fileAttachment: {
        resourceType: 'file',
        fileName: 'document.pdf',
        fileSize: 1024000,
        fileType: 'application/pdf',
        fileUrl: 'https://cdn.todoist.com/files/document.pdf',
        uploadState: 'completed',
      },
    } as Comment,
    multiline: {
      ...commentDefaults,
      id: 'comment-4',
      content: 'Line one\nLine two\nLine three\nLine four\nLine five',
      taskId: 'task-1',
      projectId: undefined,
      postedAt: '2026-01-09T17:00:00Z',
    } as Comment,
  },
  user: {
    basic: {
      id: 'user-1',
      name: 'Test User',
      email: 'test@example.com',
      inboxProjectId: 'proj-inbox',
    },
  },
}
